version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4
Branches:
  only:
    - main

jobs:
  frontend_build_test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - working_directory: ~/project/Frontend
      - run:
          name: Changing working directory
          command: |
            cd Frontend
      - run:
          name: Installing Frontend dependencies
          command: |
            npm install
            ls
            pwd
            ls ~
      - run:
          name: Frontend Tests
          command: |
            npm run test
      - run:
          name: App Build
          command: |
            npm run build
            ls
            pwd

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - frontend_build_test
