version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4
Branches:
  only:
    - main

jobs:
  frontend_build_test:
    working_directory: ~/storefront-backend/Frontend
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - run:
          name: deleting repo dir
          command: |
            rm -rf ~/storefront-backend
      - checkout:
          path: ~/storefront-backend
      - run:
          name: Installing dependencies
          command: |
            npm install
      - run:
          name: Frontend Tests
          command: |
            npm run test
      - run:
          name: App Build
          command: |
            npm run build
  backend_build_test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout:
      - run:
          name: Installing dependencies
          command: |
            npm run install
      - run:
          name: Linting
          command: |
            npm run lint
      - run:
          name: App Build
          command: |
            npm run build
      - run:
          name: Jasmine Tests
          command: |
            npm run test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - frontend_build_test
      - backend_build_test
